


export const NETWORK_REQUEST_BEGIN = "NETWORK_REQUEST_BEGIN"
export const NETWORK_REQUEST_SUCCESS = "NETWORK_REQUEST_SUCCESS"


export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";

export const LOAD_REVIEWS_FAILED = "LOAD_REVIEWS_FAILED";
export const SUBMIT_NEW_REVIEW = "SUBMIT_NEW_REVIEW"

export const BUY = "BUY"
export const CHECKOUT = "CHECKOUT"

